#!/bin/bash

cp -r ./.* ../
cp -r ./* ../
rm -rf ../.git
rm -rf ../README.md

rm -rf ~/.zsh/plugins/zsh-autosuggestions/
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/plugins/zsh-autosuggestions
source ~/.zshrc
