vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.updatetime = 150
vim.opt.signcolumn = "yes"
vim.opt.guifont = "CascadiaCode Nerd Font:h13"
vim.g.mapleader = " "
